before_script:
  # - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  # - eval $(ssh-agent -s)
  # - echo "$SSH_PRIVATE_KEY"
  # - ssh-add "$SSH_PRIVATE_KEY"
  # - ssh root@backend.dejozz.com
  # - mkdir -p ~/.ssh
  # - chmod 700 ~/.ssh
  # - ssh-keyscan backend.dejozz.com >> ~/.ssh/known_hosts 
  # - chmod 644 ~/.ssh/known_hosts
  - uname
  - whoami
  # - pwd
  - cd /opt/others/www/larahan_gitlab #your project p ath
building:
  stage: build
  script:
    - composer install
    - mkdir database/migrations/projects
    - mkdir database/migrations/alters
    - cp database/migrations/__defaults/*.* database/migrations/projects/
    - cp .env-example .env
    - chmod 777 .gitignore
    - chmod 777 .env 
    - chmod 777 -R app/Models
    - chmod 777 -R public
    - chmod 777 -R storage
    - chmod 777 -R database/migrations 
    # - git pull origin develop
    # - composer install
    # - cp .env.example .env
    # - php artisan key:generate
    # - php artisan migrate --seed
    # - php artisan cache:clear
    # - php artisan config:clear
    # - php artisan storage:link
    # - sudo chown -R deployer:www-data /opt/others/www/larahan_gitlab/
    # - find /opt/others/www/larahan_gitlab -type f -exec chmod 664 {} \;
    # - find /opt/others/www/larahan_gitlab -type d -exec chmod 775 {} \;
    # - chgrp -R www-data storage bootstrap/cache
    # - chmod -R ug+rwx storage bootstrap/cache
testing:
  stage: test
  script:
    - php ./vendor/bin/phpunit
deploying:
  stage: deploy
  script:
    - echo "Deployed"
    - php artisan queue:restart #if you use queue